<!doctype html>
<html>
    <head>
        <?php include VIEW_PATH . 'layout/header.phtml' ?>
    </head>
    <body> 
        <form method="POST" action="<?= getenv('APP_URL') ?>/admin/changepassword">
            <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
            <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
            <div class="form-group">
                <label for="name">New Password</label>
                <input type="password" class="form-control" min="8" maxlength="20" id="password" name="password" value="" required>                                           
            </div>                                    
            <div class="form-group">
                <label for="uri_link">Confirm New Password</label>
                <input type="password" class="form-control" min="8" maxlength="20" id="confirm_password" name="confirm_password" value="" required> 
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" id="change-password-submit">Save</button>
            </div>
        </form>   
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>    
</html>