<!doctype html>
<html>
    <head>
        <?php include VIEW_PATH . 'layout/header.phtml' ?>
    </head>
    <body> 
        <form method="POST" action="<?= getenv('APP_URL') ?>/admin/deleteitem/<?= $item['id'] ?>">
            <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
            <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
            <div class="form-group">
                <p><b>Are you sure you want to delete this item?</b></p>
                <p><b>Name:</b> <?= $item['name'] ?></p>                                                               
                <p><b>Price:</b> $<?= $item['price'] ?></p>                
            </div>            
            <div class="form-group">
                <button type="submit" class="btn btn-danger">Confirm</button>
            </div>
        </form>   
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>    
</html>