<!doctype html>
<html>
    <head>
        <?php include VIEW_PATH . 'layout/header.phtml' ?>
    </head>
    <body> 
        <form method="POST" action="<?= getenv('APP_URL') ?>/admin/edituser">
            <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
            <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" maxlength="255" id="name" name="name" value="<?= $user['name'] ?>" required>                                           
            </div>                                    
            <div class="form-group<?= (array_key_exists('uri_link', $errors)) ? ' has-error' : '' ?>">
                <label for="uri_link">Username</label>
                <input type="text" class="form-control" maxlength="20" id="uri_link" name="uri_link" value="<?= ($params['uri_link']) ? $params['uri_link'] : $user['uri_link'] ?>" required> 
                <?php if(array_key_exists('uri_link', $errors)): ?>
                    <span class="help-block">
                        <strong><?= $errors['uri_link'] ?></strong>
                    </span>
                <?php endif ?>
            </div>
            <div class="form-group<?= (array_key_exists('email', $errors)) ? ' has-error' : '' ?>">
                <label for="email">Email</label>
                <input type="email" class="form-control" maxlength="250" id="email" name="email" value="<?= ($params['email']) ? $params['email'] : $user['email'] ?>" required>
                <?php if(array_key_exists('email', $errors)): ?>
                    <span class="help-block">
                        <strong><?= $errors['email'] ?></strong>
                    </span>
                <?php endif ?>
            </div>
            <div class="form-group">
                <button type="submit" id="edit-user-submit" class="btn btn-primary">Save</button>
            </div>
        </form>   
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>    
</html>