<!doctype html>
<html>
    <head>
        <title>Login</title>
        <?php include VIEW_PATH . 'layout/header.phtml' ?>
    </head>
    <body>
        <?php include VIEW_PATH . 'layout/nav.phtml' ?>
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-lg-offset-3 col-md-5 col-md-offset-2 col-sm-6 col-xs-6 col-xs-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-heading">Login</div>
                        <div class="panel-body">                            
                            <div class="input-group col-lg-offset-2 col-md-offset-2 col-sm-offset-2 col-xs-offset-2">
                                <form class="form-horizontal" role="form" method="POST" action="<?= getenv('APP_URL') ?>/admin/login">
                                    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
                                    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
                                    <div class="form-group">
                                        <label for="email" class="control-label">Email</label>
                                        <input id="email" type="email" class="form-control" name="email" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="password" class="control-label">Password</label>
                                        <input id="password" type="password" class="form-control" name="password" required>
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary">Login</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
        <?php include VIEW_PATH . 'layout/footer.phtml' ?>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>    
</html>