<!doctype html>
<html>
    <head>
        <title>LuLaRoe <?= $user['name'] ?></title>
        <?php include VIEW_PATH . 'layout/header.phtml' ?>
        <link href="//cdn.rawgit.com/noelboss/featherlight/1.7.2/release/featherlight.min.css" type="text/css" rel="stylesheet" />
    </head>
    <body>
        <?php include VIEW_PATH . 'layout/nav.phtml' ?>        
        <div class="container">            
            <div class="row">
                <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-6">User Details</div>
                                <div class="col-xs-6 right"><i class="fa fa-gear fa-fw">&nbsp;</i><a href="<?= getenv('APP_URL') ?>/admin/edituser" data-featherlight="ajax">Edit</a></div>
                            </div>
                        </div>
                        <div class="panel-body">    
                            <form class="form-horizontal" role="form"> 
                                <div class="form-group">
                                    <label for="name" class="control-label col-xs-4">Name</label>
                                    <div class="col-xs-8 user_attribute"><?= $user['name'] ?></div>                                             
                                </div>                                    
                                <div class="form-group">
                                    <label for="uri_link" class="control-label col-xs-4">Username</label>
                                    <div class="col-xs-8 user_attribute"><?= $user['uri_link'] ?></div>   
                                </div>
                                <div class="form-group">
                                    <label for="email" class="control-label col-xs-4">Email</label>
                                    <div class="col-xs-8 user_attribute"><?= $user['email'] ?></div>   
                                </div>
                                <div class="form-group">
                                    <label for="email" class="control-label col-xs-4">Password</label>
                                    <div class="col-xs-8 user_attribute"><a href="#" data-featherlight="<?= getenv('APP_URL') ?>/admin/changepassword">Change Password</a></div>   
                                </div>
                            </form>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
        <?php include VIEW_PATH . 'layout/footer.phtml' ?>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="//cdn.rawgit.com/noelboss/featherlight/1.7.2/release/featherlight.min.js" type="text/javascript" charset="utf-8"></script>
    </body>    
</html>