<!doctype html>
<html>
    <head>
        <?php include 'header.phtml' ?>
    </head>
    <body>
        <?php include 'nav.phtml' ?>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">Oops!</div>
                        <div class="panel-body">
                            <h2>Page Not Found!</h2>
                            <p><?= $message ?></p>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
        <?php include 'footer.phtml' ?>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>    
</html>