<div class="row">
    <div class="footer">
        <div class="container">                
            <p class="text-muted">
                Copyright &copy;<?= date("Y") ?> AML Consulting, LLC | All Rights Reserved | <a href="mailTo:alex@amlconsulting.net">Contact Support</a>
                <br>
                LuLaRoe logo is property of LuLaRoe, and this website does not represent LuLaRoe.
            </p>
        </div>
    </div>
</div>