<!doctype html>
<html>
    <head>
        <?php include 'header.phtml' ?>
    </head>
    <body>
        <?php include 'nav.phtml' ?>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">Discounted Pricing</div>
                        <div class="panel-body">                            
                            <?php if(!$items): ?>
                                <p><?= $user['name'] ?> doesn't have any items. If you feel this is in error, please contact <?= $user['name'] ?> at <a href="mailTo:<?= $user['email'] ?>"><?= $user['email'] ?></a></p>
                            <?php else: ?>
                                <p>Below are my current discounted prices for my LuLaRoe inventory. Thanks for stopping by!</p>
                            <?php endif ?>
                        </div>
                        <ul class="list-group">
                            <?php foreach($items as $item): ?>
                                <li class="list-group-item">
                                    <span class="badge">$<?= $item['price'] ?></span> <?= $item['name'] ?>
                                </li>
                            <?php endforeach ?>
                        </ul>
                        <div class="panel-footer">
                            <p>NOTE: These prices are only available when shopping from LuLaRoe <?= $user['name'] ?>. They do not represent the price guide provided by LuLaRoe or any other consultants. These prices are subject to change at any time.</p>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
        <?php include 'footer.phtml' ?>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>    
</html>