<div class="row">
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">   
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <div class="navbar-brand-name">
                        <img src="images/logo.png"/> LuLaRoe <?= $user['name'] ?>
                    </div>
                </a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="mailTo:<?= $user['email'] ?>">Contact <?= $user['name'] ?></a></li>                   
                </ul>
            </div>
        </div>                
    </nav>
</div>    