<div class="row">
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header"> 
                <?php if($user): ?>  
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                <?php endif ?>
                <a class="navbar-brand" href="#">
                    <div class="navbar-brand-name">
                        <img src="<?= getenv('APP_URL') ?>/images/logo.png"/><?php if($user): ?><?= $user['name'] ?><?php endif ?>
                    </div>
                </a>
            </div>
            <?php if($user): ?>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <?php if($loggedIn): ?>
                            <li><a href="<?= getenv('APP_URL') ?>/admin/items">Items</a></li>
                            <li><a href="<?= getenv('APP_URL') ?>/admin/user">Profile</a></li>
                            <li><a href="<?= getenv('APP_URL') ?>/admin/logout">Logout</a></li>                   
                        <?php else: ?>
                            <li><a href="mailTo:<?= $user['email'] ?>">Contact <?= $user['name'] ?></a></li>                   
                        <?php endif ?>
                    </ul>
                </div>
            <?php endif ?>
        </div>                
    </nav>
</div>    